# Generated by Django 4.2.2 on 2023-07-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DniNoExist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_distrito', models.CharField(max_length=5, verbose_name='Número Distrito')),
                ('num_circuito', models.CharField(max_length=5, verbose_name='Número Circuito')),
                ('num_mesa', models.CharField(max_length=3, verbose_name='Número Mesa')),
                ('num_orden', models.CharField(max_length=4, verbose_name='Número Orden')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'dninoexist',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(blank=True, null=True, verbose_name='DNI')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio')),
                ('departamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento')),
                ('nombre_circuito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Circuito')),
                ('codigo_circuito', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Circuito')),
                ('mesa', models.IntegerField(blank=True, null=True, verbose_name='Número Mesa')),
                ('voto', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Votó')),
            ],
            options={
                'db_table': 'padron',
                'ordering': ['id'],
            },
        ),
    ]
