# Generated by Django 4.2.2 on 2023-07-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='padron',
            options={'managed': False, 'ordering': ['id']},
        ),
    ]
