# Generated by Django 4.2.2 on 2023-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(blank=True, null=True, verbose_name='DNI')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio')),
                ('departamento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Departamento')),
                ('circuito', models.CharField(blank=True, max_length=8, null=True, verbose_name='Circuito')),
                ('nombre_circuito', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Circuito')),
                ('voto', models.SmallIntegerField(blank=True, default=1, null=True, verbose_name='Votó')),
            ],
            options={
                'db_table': 'padrones',
                'ordering': ['id'],
            },
        ),
    ]
