# Generated by Django 4.2.2 on 2023-07-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_padron_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DniNoExist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_distrito', models.CharField(max_length=5, verbose_name='Número Distrito')),
                ('num_circuito', models.CharField(max_length=5, verbose_name='Número Circuito')),
                ('num_mesa', models.CharField(max_length=3, verbose_name='Número Mesa')),
                ('num_orden', models.CharField(max_length=4, verbose_name='Número Orden')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'dninoexist',
                'ordering': ['num_distrito'],
            },
        ),
    ]
