# Generated by Django 4.2.2 on 2023-07-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_padron'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='padron',
            table='padron',
        ),
    ]
