# Generated by Django 4.2.2 on 2023-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_dninoexist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dninoexist',
            name='dni',
            field=models.CharField(max_length=10, unique=True, verbose_name='DNI'),
        ),
    ]
